export enum AccountType {
    ADMIN = 'admin',
    ACCOUNT = 'account',
}

export enum AccountRights {
    AUTH_CONFIRM_ACCOUNT = 'confirm_account',
    AUTH_SEND_CODE = 'send_code',
    READ_EVENT_BY_ID = 'read_event_by_id',
    ACCOUNT_BY_ID = 'my_account',
    UPDATE_OWN_ACCOUNT = 'update_own_account',
    READ_VERIFICATION_PRICE = 'read_verification_price',
    SEND_VERIFICATION_CODE_VIA_EMAIL = 'send_verification_code_via_email',
    SEND_VERIFICATION_CODE_VIA_PHONE = 'send_verification_code_via_phone',
    VALIDATE_CONFIRMATION_CODE = 'validate_confirmation_code',
    CREATE_BUSINESS_CARD = 'create_business_card',
    READ_BUSINESS_CARD_LIST = 'read_business_card',
    READ_BUSINESS_CARD_BY_ID = 'read_business_card_by_id',
    UPDATE_BUSINESS_CARD = 'update_business_card',
    DELETE_BUSINESS_CARD = 'delete_business_card',
    CREATE_BUSINESS_CARD_EMAIL = 'create_business_card_email',
    READ_BUSINESS_CARD_EMAILS = 'read_business_card_emails',
    READ_BUSINESS_CARD_EMAIL_BY_ID = 'read_business_card_email_by_id',
    UPDATE_BUSINESS_CARD_EMAIL = 'update_business_card_email',
    DELETE_BUSINESS_CARD_EMAIL = 'delete_business_card_email',
    CREATE_BUSINESS_CARD_PHONE = 'create_business_card_phone',
    READ_BUSINESS_CARD_PHONES = 'read_business_card_phones',
    READ_BUSINESS_CARD_PHONE_BY_ID = 'read_business_card_phone_by_id',
    UPDATE_BUSINESS_CARD_PHONE = 'update_business_card_phone',
    DELETE_BUSINESS_CARD_PHONE = 'delete_business_card_phone',
    CREATE_BUSINESS_CARD_WEBSITE = 'create_business_card_website',
    READ_BUSINESS_CARD_WEBSITES = 'read_business_card_websites',
    READ_BUSINESS_CARD_WEBSITE_BY_ID = 'read_business_card_website_by_id',
    UPDATE_BUSINESS_CARD_WEBSITE = 'update_business_card_website',
    DELETE_BUSINESS_CARD_WEBSITE = 'delete_business_card_website',
    READ_BUSINESS_CARD_CONTACTS = 'read_business_card_contacts',
    CREATE_BUSINESS_CARD_CONTACT = 'create_business_card_contact',
    READ_BUSINESS_CARD_CONTACT_BY_ID = 'read_business_card_contact_by_id',
    UPDATE_BUSINESS_CARD_CONTACT = 'update_business_card_contact',
    DELETE_BUSINESS_CARD_CONTACT = 'delete_business_card_contact',
    UPLOAD_PROFILE_PHOTO = 'upload_profile_photo',
    READ_OWNED_SUBSCRIPTION_LIST = 'read_owned_subscriptions_list',
    CREATE_SUBSCRIPTION = 'create_subscription',
    UPDATE_SUBSCRIPTION = 'update_subscription',
    DELETE_OWN_ACCOUNT = 'delete_own_account',
}

export const accountRights = [
    AccountRights.AUTH_CONFIRM_ACCOUNT,
    AccountRights.AUTH_SEND_CODE,
    AccountRights.READ_EVENT_BY_ID,
    AccountRights.ACCOUNT_BY_ID,
    AccountRights.READ_VERIFICATION_PRICE,
    AccountRights.SEND_VERIFICATION_CODE_VIA_EMAIL,
    AccountRights.SEND_VERIFICATION_CODE_VIA_PHONE,
    AccountRights.VALIDATE_CONFIRMATION_CODE,
    AccountRights.CREATE_BUSINESS_CARD,
    AccountRights.READ_BUSINESS_CARD_LIST,
    AccountRights.READ_BUSINESS_CARD_BY_ID,
    AccountRights.UPDATE_BUSINESS_CARD,
    AccountRights.DELETE_BUSINESS_CARD,
    AccountRights.CREATE_BUSINESS_CARD_EMAIL,
    AccountRights.READ_BUSINESS_CARD_EMAILS,
    AccountRights.READ_BUSINESS_CARD_EMAIL_BY_ID,
    AccountRights.UPDATE_BUSINESS_CARD_EMAIL,
    AccountRights.DELETE_BUSINESS_CARD_EMAIL,
    AccountRights.CREATE_BUSINESS_CARD_PHONE,
    AccountRights.READ_BUSINESS_CARD_PHONES,
    AccountRights.READ_BUSINESS_CARD_PHONE_BY_ID,
    AccountRights.UPDATE_BUSINESS_CARD_PHONE,
    AccountRights.DELETE_BUSINESS_CARD_PHONE,
    AccountRights.CREATE_BUSINESS_CARD_WEBSITE,
    AccountRights.READ_BUSINESS_CARD_WEBSITES,
    AccountRights.READ_BUSINESS_CARD_WEBSITE_BY_ID,
    AccountRights.UPDATE_BUSINESS_CARD_WEBSITE,
    AccountRights.DELETE_BUSINESS_CARD_WEBSITE,
    AccountRights.READ_BUSINESS_CARD_CONTACTS,
    AccountRights.CREATE_BUSINESS_CARD_CONTACT,
    AccountRights.READ_BUSINESS_CARD_CONTACT_BY_ID,
    AccountRights.UPDATE_BUSINESS_CARD_CONTACT,
    AccountRights.DELETE_BUSINESS_CARD_CONTACT,
    AccountRights.UPLOAD_PROFILE_PHOTO,
    AccountRights.UPDATE_OWN_ACCOUNT,
    AccountRights.READ_OWNED_SUBSCRIPTION_LIST,
    AccountRights.CREATE_SUBSCRIPTION,
    AccountRights.UPDATE_SUBSCRIPTION,
    AccountRights.DELETE_OWN_ACCOUNT,
]

export const adminRights = [...accountRights]
